language: cpp
sudo: false

addons:
  coverity_scan:
    project:
      name: "UrusTeam/URUS"
      description: "Build submitted via Travis CI"
    notification_email: htakey@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
    
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - ubuntu-toolchain-r-test
#      - george-edison55-cmake-3.x
#      - llvm-toolchain-precise-3.7
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
#      - clang-3.7
#      - llvm-3.7

cache:
  ccache: true
  directories:
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export CI_CRON_JOB=1 ; fi

script:
  - python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle APMrover2
  - python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle AntennaTracker
  - python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduCopter
  - python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduPlane
  - python Tools/autotest/param_metadata/param_parse.py --no-emit --vehicle ArduSub
  - Tools/scripts/build_ci.sh

before_cache:
  - ccache -z

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8848f8ec591a1632f13b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

compiler:
  - gcc
#  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "i5uFcdAj9O5MRjNYb1077rtfowIcPTYtyOxUZck906PxXerA2mTfAych5AWAxhD6vZ/TYibgsh2KMB+qMkcfLIZPvvMxAi4PjiydBWDohlpL3/IfafvX2PGeG1kae1NBOqBuxnalUqJhlXNXuCpXmOfz0wZsavdmlfFbqfoZq+RPx9d4IOHtdBOKunxHJ2MFHLQ8vGLp3watrgCGRSaMZhl9YFvP0AGO7aQxz7Nl4kf8ZTU2eIuPTn8OnuWpb31dxP0uZ/h4UC0mFhGsa6kaQcYTHLnhBK4HQmwi5JrMut4crojXvtKWnf+28VCr75qcHM2a/Lk22jENc2/SbxFiLtxFD/OS/dL2kU61h1U6TMzMjXfDbgU73cySaIosnotn25YZ+d3giHf2FvJ211GFxR5lGrbJbKN3+dPHQV/16nCaq0OfcegzEOaR7qCkNkeUjzf13cLWzevzv94gnr4w820qerC5iIjjmcadx+LZHgrj4jnsve5wK2elQ3fFgij0wsShnaI3++rUorN7nxKXGqSMQuWgVzAgCf16DlhNgxaOJl6dRYgh8cOAbBQ0IbQT0WdhYfxSOTdmmF2dKL9Mbm6XZgzDkd/2HbsLFxDKzV7nv9Kyri8XKn81Y9QvHMp78cdcQfhJqmuHV2hmYooWnH3gvg1zDVGcJ9rJyjSlwg0="

matrix:
  fast_finish: true
  include:
    - compiler: "gcc"
      env: CI_BUILD_TARGET="sitl minlure linux navio2 bebop"
    - compiler: "gcc"
      env: CI_BUILD_TARGET="px4-v2 px4-v4"
    - compiler: "gcc"
      env: CI_BUILD_TARGET="px4-v3"
    - compiler: "gcc"
      env: CI_BUILD_TARGET="sitltest"
